### ISSUE TITLE
Use specific CipherSuites

### ISSUE THREAD

**Issue by 89z** [lesismal/llib#11]
If I use the below program, extra CipherSuites are added, and the order is different:

~~~
["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_CHACHA20_POLY1305_SHA256",
"TLS_AES_128_GCM_SHA256","TLS_AES_256_GCM_SHA384"],
~~~

is it possible for a client to set a list in a specific order, and not have it altered by the package? I have encountered servers (for example `android.clients.google.com`) that will return `403 Forbidden` if CipherSuites sent by the client is in the wrong order.

~~~go
package main

import (
   "bufio"
   "github.com/lesismal/llib/std/crypto/tls"
   "net/http"
   "os"
)

func main() {
   req, err := http.NewRequest("GET", "https://www.howsmyssl.com/a/check", nil)
   if err != nil {
   panic(err)
   }
   cfg := &tls.Config{
      CipherSuites: []uint16{
         0x1302, // TLS_AES_256_GCM_SHA384
         0xC02C ,// TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      },
      ServerName: req.URL.Host,
   }
   conn, err := tls.Dial(
   "tcp", req.URL.Host+":"+req.URL.Scheme, cfg,
   )
   if err != nil {
      panic(err) 
   }
   if err := req.Write(conn); err != nil {
      panic(err)
   }
   res, err := http.ReadResponse(bufio.NewReader(conn), req)
   if err != nil {
      panic(err) 
   }
   defer res.Body.Close()
   os.Stdout.ReadFrom(res.Body)
}
~~~

**Comment by lesismal** [comment]
> ```go
> CipherSuites
> ```

You can set the CipherSuites yourself and it seems that the client sends the CipherSuites in order :
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_client.go#L146
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_client.go#L85
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_client.go#L121

I copied the code of go 1.16, and only rewrite it to support non-blocking, so it should behave the same as std.
So, have you met the 403 or just want to ask whether you can set the CipherSuites yourself? Does std tls run fine?

**Comment by 89z** [comment]
> You can set the CipherSuites yourself and it seems that the client sends the CipherSuites in order :

No, they are not in order, see original post.

> So, have you met the 403

Yes, I tried a request and response was 403 Forbidden. Then I tried with another package, and response was 200 OK.

> Does std tls run fine?

std TLS is broken also, so I am trying to find a package that works.

**Comment by lesismal** [comment]
maybe here removes some of the value you have set:
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_client.go#L89

**Comment by lesismal** [comment]
seems the same problem as: https://github.com/golang/go/issues/48207

**Comment by 89z** [comment]
thank you, I will find another solution

**Comment by lesismal** [comment]
I have just make a new branch, please try it, let's check whether it works:
https://github.com/lesismal/llib/commit/095c0981ed2c5532ef1ca4bc63fd1440ef47ebe4

go get -u github.com/lesismal/llib@095c0981ed2c5532ef1ca4bc63fd1440ef47ebe4

**Comment by 89z** [comment]
I dont think it worked, I got same result. Here is my version:

~~~
github.com/lesismal/llib v1.1.1-0.20210908153217-095c0981ed2c
~~~

**Comment by lesismal** [comment]
All right, please let me know if you find another resolution. And if you could provide a server code that can reproduce this problem, I'd like trying to debug it.

**Comment by 89z** [comment]
Here is request that I am trying to do:

~~~
POST /auth HTTP/1.1
Host: android.clients.google.com
User-Agent: Go-http-client/1.1
Content-Length: 240
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

sdk_version=17&Email=srpen6%40gmail.com&EncryptedPasswd=AFcb4KTD0IhjQFmNOtCgA_caa-UxY78YtpJzSdCFjHPmvHxV7mV-wyQuf_m9b1yoYkuPe9AB...%3D%3D
~~~

I was finally able to get it to work, using this TLS fingerprint:

- https://github.com/89z/gpsoauth/blob/27697e35/cipher.go
- https://github.com/89z/gpsoauth/blob/27697e35/hello.go

**Comment by lesismal** [comment]
thanks
