### ISSUE TITLE
update cespare/xxhash to v2

### ISSUE THREAD

**Issue by hellodword** [lesismal/llib#18]
谢谢作者的 nbio。

这是一个不那么正经的请求：现在用的 cespare/xxhash v1.1.0 会引入新的依赖，升级后会"干净"一些

（要是 nbio 也能进化为 zero dependency 那就更好了）

![image](https://user-images.githubusercontent.com/46193371/195844747-03eac2ec-b6fa-4665-9d1b-877bc10be33a.png)

**Comment by lesismal** [comment]
感谢关注！

这个依赖xxhash的map其实只有实现，目前还没有被我其他代码中使用，所以其实可以删掉。。

nbio的依赖其实只有llib，其实最找是想把llib内置在nbio的，但是llib的许可证是BSD-3，而nbio是MIT，迫于无奈，把llib拆出来了。
早期的时候examples也是内置在nbio里的，但是依赖也是很多，后来拆出来确实干净了一些。

要不我把xxhash和其他一些没用到的代码先删掉？

**Comment by lesismal** [comment]
删掉了，发了个 [v1.1.8](https://github.com/lesismal/llib/releases/tag/v1.1.8)
现在依赖只剩下 `golang.org/x` 相关了

nbio提交更新了llib版本到1.1.8，但是因为没有功能发布，暂时不发新版本，攒一攒其他改动再发布

**Comment by lesismal** [comment]
> 原来如此，没有意识到和许可证有关

因为go是 [BSD-3](https://github.com/golang/go/blob/master/LICENSE)，而llib里这个tls是直接拷贝标准库魔改的，所以得给它也用BSD-3，实属无奈，我其实挺喜欢 zero dependency 的，另一个项目里就是 zero dependency 的
