### ISSUE TITLE
WinHttp client can't connect to nbio TLS server

### ISSUE THREAD

**Issue by acgreek** [lesismal/llib#2]
This is something I am trying to figure out. No problems with any other clients, but we have one developer that has a c++ app that is using winhttp api to establish a websocket to my nbio TLS server and it appears the nbio server isn't reading the client tls key exchange packet, it is re-sending the 'server Hello done' after a tcp timeout. The client is able to connect to a very basic gorrilla tls websocket server I wrote simply to determine if the problem is isolated to nbio

**Comment by acgreek** [comment]
I also add that winhttp is successfully connecting when tls is disabled in the client and server

**Comment by acgreek** [comment]
here is a pcap stream of the connection 
[example.pcapng.gz](https://github.com/lesismal/llib/files/6593123/example.pcapng.gz)

**Comment by lesismal** [comment]
> here is a pcap stream of the connection
> [example.pcapng.gz](https://github.com/lesismal/llib/files/6593123/example.pcapng.gz)

I tried [this client](https://github.com/lesismal/nbio/blob/master/examples/tls/client_std/client.go#L10) with VersionTLS12, it works fine. working on it.

```golang
tlsConfig := &tls.Config{
	InsecureSkipVerify: true,
	MinVersion:         tls.VersionTLS12,
	MaxVersion:         tls.VersionTLS12,
}
```

**Comment by lesismal** [comment]
problem located here:
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_server.go#L868

working on it.

**Comment by lesismal** [comment]
fixed:  https://github.com/lesismal/llib/commit/d120a1b3a60c2db4d9a0d4f7d5e894ef2fa5c5c3

sorry for this stupid enum state value

**Comment by acgreek** [comment]
NP, thanks for figuring it out. Appears to work for the simple test clients servers; will test with my larger app shortly. Any idea as to why this bug wasn't preventing other clients from connecting via tls?

**Comment by lesismal** [comment]
> NP, thanks for figuring it out. Appears to work for the simple test clients servers; will test with my larger app shortly. Any idea as to why this bug wasn't preventing other clients from connecting via tls?

for tls1.2, the server side returns before send changeCipherSpec msg due to a wrong value of stateServerHandshakeSendFinished2:
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_server.go#L1006

**Comment by lesismal** [comment]
I also have two commits to optimize batch write during tls handshake after https://github.com/lesismal/llib/commit/d120a1b3a60c2db4d9a0d4f7d5e894ef2fa5c5c3

then we get these batch packets in Wireshark:

![image](https://user-images.githubusercontent.com/40462947/120821314-f06f1280-c587-11eb-9958-7195e086f87f.png)

the handshake messages were sent separately before as we got in your pre example:
![image](https://user-images.githubusercontent.com/40462947/120821573-2dd3a000-c588-11eb-9f7f-e7818b086377.png)

**Comment by lesismal** [comment]
> Any idea as to why this bug wasn't preventing other clients from connecting via tls?

only versions below 1.3 are affected, if other clients support 1.3, server and client will select 1.3.

and maybe some other clients using tls version below 1.3 change the ticket https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_server.go#L135
then would not enter this bug branch:
https://github.com/lesismal/llib/blob/master/std/crypto/tls/handshake_server.go#L164

need more debug for details.
