### ISSUE TITLE
为什么去掉了tls库的自定义内存分配器？

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/llib#21]
目前在做wss代理，目前看是使用了原生的内存申请，请问是出于什么考虑？

**Comment by lesismal** [comment]
我不确定是不是哪里有bug，用Pool可能有重复Put导致单个buffer被不同地方Get出来然后内存就脏了会有bug，这块有点复杂，所以需要很多精力去重新搞一轮甚至更多。之前搞这块身体伤到了，所以暂时没有体力去把这块重来一遍。得等体力够了再重新来搞一轮。

如果有兴趣可以一块来搞一下。

**Comment by liangmanlin** [comment]
> 我不确定是不是哪里有bug，用Pool可能有重复Put导致单个buffer被不同地方Get出来然后内存就脏了会有bug，这块有点复杂，所以需要很多精力去重新搞一轮甚至更多。之前搞这块身体伤到了，所以暂时没有体力去把这块重来一遍。得等体力够了再重新来搞一轮。
> 
> 如果有兴趣可以一块来搞一下。

ok，我也搞点测试环境试试

**Comment by lesismal** [comment]
本来还想做更多尝试的，比如nbio poller那块接入openssl，工作量也是不小，暂时没体力。

还有为了内存更可控、使用cgo buffer然后也可以方便接入tcmalloc/jemalloc那些，但手动分配释放必须一对一也是比较麻烦，怕有不小心就漏掉释放，所以最近尝试搞了个不需要精确一对一、通过Finalizer等gc的时候自动释放的，这样的话应用尽量确保释放但不强求一对一，能减轻点心智负担：
https://github.com/lesismal/noleak
但是要用 *[]byte 也是需要一轮大改，暂时也是没体力弄。
由于已经有 debug.SetMemoryLimit，所以暂时好像也还好，我就先歇歇。。。

**Comment by liangmanlin** [comment]
测试了400个wss链接，100ms收发数据，使用tls.ResetConn替换了分配器，暂时没有发现重复put的地方，有没有测试用例参考

**Comment by liangmanlin** [comment]
运行中不会，但是在关闭测试客户端的时候确实触发了重复put，我的用法确实会调用2次close，但是我看tls.Conn.Close是有锁的，这就异常诡异了

**Comment by lesismal** [comment]
我也记不清了，一些llib/tls的一些中间版本我测试失败所以回滚了之类的。
后面有空了再试下。这里有个mempool的debug版本，可以打印统计、调用栈的，调试的话可以用这个试试定位bug：
https://github.com/lesismal/mempooldebug/blob/master/mempooldebug.go#L283

**Comment by liangmanlin** [comment]
> 我也记不清了，一些llib/tls的一些中间版本我测试失败所以回滚了之类的。 后面有空了再试下。这里有个mempool的debug版本，可以打印统计、调用栈的，调试的话可以用这个试试定位bug： https://github.com/lesismal/mempooldebug/blob/master/mempooldebug.go#L283

ok,我试试

**Comment by liangmanlin** [comment]
https://github.com/liangmanlin/example/blob/master/mempool.go#L65

由于内网的原因，没有办法很好给出测试的程序，我现在把内存分配器拿到了外网（手敲的，不一定完全正确）

同时打开了这段代码

https://github.com/lesismal/llib/blob/09ffa8a27ccd00bdc65a918f24228db7548c2d54/std/crypto/tls/tls.go#L46-L53

发现并没有重复put，有没有可能是当时使用的内存分配器有问题

**Comment by lesismal** [comment]
> 发现并没有重复put，有没有可能是当时使用的内存分配器有问题

也有可能，我这两天也跑了几轮压测，也没有复现出来。

**Comment by liangmanlin** [comment]
如果测试正常，希望nbio可以使用支持的版本，因为目前做密集io，这个部分的消耗不小

**Comment by lesismal** [comment]
> 如果测试正常，希望nbio可以使用支持的版本，因为目前做密集io，这个部分的消耗不小

llib 里可以先恢复使用传入的参数作为allocator，然后nbhttp里创建时默认传入 llib/tls 的Allocator，但这个是用户可配置的、用户自己修改即可，以前是这种机制，llib怀疑有bug才去掉了

**Comment by lesismal** [comment]
> 这里似乎有问题，outBuf  是使用分配器分配的，但是中间会被 sliceForAppend函数重新赋值，导致脱离了分配器

http/websocket部分也有一些是append、修改了的，不保证原样取出原样放回。
所以目前版本都是不能直接使用c allocator的。

**Comment by liangmanlin** [comment]
这样啊，是出于什么考虑呢，因为之前的版本我可以多分配若干字节，这样我在写入另外一个地方的时候，不需要copy

```golang
buf := make([]byte,size+4)
return buf[4:]
```

这样我就有4个字节的操作空间

**Comment by lesismal** [comment]
没看懂你这里说的是什么

**Comment by liangmanlin** [comment]
我做的是wss代理，代理会把收到的wss数据通过tcp发往内网的机器上，这里需要给数据标记一个长度，通常是2个字节。

常规的做法就是收到websocket的数据后，重新申请一个内存块，大小等于ws数据长度+2，这样在头2个字节可以写入一个长度。

我就是在内存分配的时候，多申请两个字节，这样我拿到data后，只需要向前索引2个字节，填入长度，就不需要再申请内存，再copy数据。

不知道这样你能不能理解

**Comment by lesismal** [comment]
BodyAllocator 应该是不受今天这个修改的影响的

**Comment by liangmanlin** [comment]
> BodyAllocator 应该是不受今天这个修改的影响的

good，这样就可以完美解决了

**Comment by liangmanlin** [comment]
dev版本偶尔会发生如下错误

`nbhttp.engine.go:527 parser.Read failed: websocket: reserved bit set it frame`

**Comment by lesismal** [comment]
那应该就是allocator的问题了，之前我遇到的就有这种

**Comment by lesismal** [comment]
dev我先恢复到昨天之前了。就用 debug.SetMemoryLimit 应该还好

**Comment by liangmanlin** [comment]
我尝试回退到nbio v1.3.10 似乎也是有找一个问题，我检查一下我自己的代码

**Comment by lesismal** [comment]
nbio也升到最新版吧

**Comment by liangmanlin** [comment]
> nbio也升到最新版吧

更新到最新问题解决
